addons:
  artifacts:
    debug: true
    paths:
    - libs.zip
    - build.zip
    - testbuild.zip
    - jacoco.exec
    target_paths: 8b3360c4-2c82-4d82-8cf8-9e33fa480f81
after_success:
- ' wget --content-disposition http://search.maven.org/remotecontent?filepath=org/jacoco/jacoco/0.7.7.201606060606/jacoco-0.7.7.201606060606.zip '
- ' unzip -o jacoco-0.7.7.201606060606.zip  '
- ' cd lib  '
- ' mv * ../  '
- ' cd ..  '
- ' chmod a+x *  '
- ' cd $PWD  '
- ' rm  ''jacoco.exec'''
- ' export JAVA_TOOL_OPTIONS=-javaagent:$PWD/jacocoagent.jar=destfile=$PWD/jacoco.exec,append=true  '
- ' travis_wait 360 mvn  test -Dmaven.test.failure.ignore=true -Djacoco.skip=true
  -Dcobertura.skip=true -Dmaven.clover.skip=true -Dmaven.javadoc.skip=true -Drat.skip=true
  -Drat.ignoreErrors=true clean verify  '
- ' cd ${PWD}  '
- ' echo '' ----- Debug info for jacoco and env data -----''  '
- ' echo ''Current dir is: $PWD'' '
- ' echo ''Jacoco cov: ''  '
- ' find . -name ''*.exec''  '
- ' echo '' ----------------------------------------------'' '
- ./df-build.sh
before_install:
- wget http://dl.google.com/android/android-sdk_r20.0.3-linux.tgz
- tar -zxf android-sdk_r20.0.3-linux.tgz
- export ANDROID_HOME=~/builds/JakeWharton/ActionBarSherlock/android-sdk-linux
- export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools
- TOOLS=$(android list sdk --no-ui | grep "Android SDK Platform-tools" | cut -d"-"
  -f1)
- android update sdk --filter "$TOOLS" --no-ui --force
- SDK=$(android list sdk --no-ui | grep ", API 14," | cut -d"-" -f1)
- android update sdk --filter "$SDK" --no-ui --force
branches: ''
cache:
  directories:
  - $HOME/.m2
jdk:
- oraclejdk8
language: java
notifications:
  webhooks:
    on_failure: always
    on_start: always
    on_success: always
    urls:
    - http://insights-portal-insights-service-webserver-dev.public-swarm.devfactory.com/travisWebHookListener?build_id=8b3360c4-2c82-4d82-8cf8-9e33fa480f81
script:
- mvn test-compile -Dgpg.skip=true -Dlicense.skip=true
# Modified by Insights Service at 2016-11-09 17:46:54.699447
